/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javasample;

import com.sun.jna.Pointer;

public class App {
    public static void main(String[] args) {
        // get pointer reference from native lib
        Pointer pointer = Rustffi.instance.hello();
        // retrive string from pointer
        String hello = pointer.getString(0);
        // send back pointer to rust to clear memory
        Rustffi.instance.freemem(pointer);
        // use string
        System.out.println(hello);
    }
}
